import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

// import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const JosefinSans = Josefin_Sans({
  weight: "200",
  style: "normal",
  subsets: ["latin"],
  variable: "--font-JosefinSans"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Logo() {
  // const imgPath = '/images/dokkyo-info-logo.png'
  const imgPath = '/images/clubs/article/logo.png'

  return (
    <div className={`${JosefinSans.className} text-4xl md:text-5xl lg:text-6xl py-4 px-4`}>
      {/* <img
        src={imgPath}
        alt="Logo"
        className="block w-[100px] aspect-[2/1] object-cover"
      /> */}
      <h1
      >
        Dokkyo-Info.
      </h1>
    </div>

  )
}

export function Header() {

  return (
    <div className="flex justify-between item-center size-auto">
      <Link
        href={'/'}
        className="object-fit"
      >
        <Logo />
      </Link>
      <section className={"flex px-5 gap-5 py-5 h-fit"}>
        <div className={` ${JosefinSans.className} hidden md:flex gap-x-3 text-sm md:text-lg lg:text-2xl list-none gap-x-5 font-light ${JosefinSans.className}`}>
          <Link href='/'>Home</Link>
          <Link href='/clubs'>Clubs</Link>
          <Link href='/semi'>Seminar</Link>
          <Link href='/article'>Article</Link>
          <Link href='/other'>Other</Link>
        </div>
        <Link href={'blog/'} className={`btn bg-blue-500 p-1 w-auto h-[30px] ${JosefinSans.className} rounded-sm`}>
          Sign In
        </Link>
        {/* <FontAwesomeIcon icon={byPrefixAndName.fas['bars']} /> */}
      </section>

    </div>
  )
}




// export function Header() {
//   return (
//     <header className="flex items-center justify-between h-20 px-8 bg-white shadow-md">

//       <Logo />

//       <nav className="hidden md:flex items-center gap-8 text-gray-700 font-medium">
//         <Link href="/">Home</Link>
//         <Link href="/clubs">Club</Link>
//         <Link href="/seminar">Seminar</Link>
//         <Link href="/article">Article</Link>
//         <Link href="/calendar">Calendar</Link>
//       </nav>

//       <Link
//         href="/blog"
//         className="bg-violet-500 text-white px-4 py-2 rounded-md hover:bg-violet-600 transition"
//       >
//         Sign In
//       </Link>
//     </header>
//   )
// }

// function Logo() {
//   const imgPath = '/images/dokkyo-info-logo.png'

//   return (
//     <div>
//       <img
//         src={imgPath}
//         alt="Logo"
//         className="block w-[120px] object-contain"
//       />
//     </div>
//   )
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta charSet="utf-8" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f2f1ec]`}
      >

        <Header />
        <main>
          {children}
        </main>

        <Menu />

        {/* <Footer /> */}
        <footer className="bg-[#141b2e] text-[#8593a8] text-center py-6 mt-16 gap-y-10">
          <section className="w-fit h-fit item-center justify-center m-auto bg-[#232E40] py-4 px-3 md: py-3, px-4 gap rounded-[7px]">

            <div className="flex justify-center pb-3">
              <div className="animate-pulse h-3 w-3 bg-blue-500 rounded-full"></div>
            </div>
            <p className="text-sm md:text-normal">Server Running...</p>
          </section>

          <p className="text-sm pt-5 pb-30 md:pb-0">
            © 2026 Dokkyo-Info. All rights reserved.
          </p>
        </footer>

      </body>
    </html>
  );
}

function Menu(){
  return(
    <div className=" m-0 justify-center md:hidden fixed bottom-10 w-2/3 rounded-full h-5 bg-lime-600">

    </div>
  )
}

// export function movingDot() {

//   type Coordinate = {
//     x: number;
//     y: number;
//   };

//   const [dotPosition, setDotPosition] = useState<Coordinate>({
//     x: 0,
//     y: 0
//   });

//   return (
//     <div
//       onPointerMove={e => {
//         setDotPosition({
//           x: e.clientX,
//           y: e.clientY
//         });
//       }}
//     />
//   )
// }


// white, red, orange, amber, yellowlime, green,
// emerable, teal, cyan, sky, blue, indigo, violet, 
// purple, fuchsia, pink, rose, slate, gray, zinc, 
// neutral, stone, mauve, olive, mist, taupe, 