import type { Metadata } from "next";
import { Geist, Geist_Mono, Ubuntu } from "next/font/google";
import Link from "next/link";
import { Josefin_Sans, Noto_Sans_JP, Kosugi_Maru } from "next/font/google";
import "./globals.css";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faHouse } from "@fortawesome/free-regular-svg-icons"
import { faPeopleRobbery, faChalkboardUser, faSchool } from "@fortawesome/free-solid-svg-icons";

config.autoAddCss = false

// import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const UbuntuFont = Ubuntu({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-Ubuntu"
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const KosugiMaru = Kosugi_Maru({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-KosugiMaru"
})

const JosefinSans = Josefin_Sans({
  style: "normal",
  subsets: ["latin"],
  variable: "--font-JosefinSans"
})

const NotoSansJp = Noto_Sans_JP({
  style: "normal",
  subsets: ["latin"],
  variable: "--font-NotoSansJp"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Logo() {
  // const imgPath = '/images/dokkyo-info-logo.png'
  const imgPath = '/images/clubs/article/logo.png'

  return (
    <div className={`${JosefinSans.className} text-4xl md:text-5xl lg:text-6xl py-4 px-4 font-light`}>
      {/* <img
        src={imgPath}
        alt="Logo"
        className="block w-[100px] aspect-[2/1] object-cover"
      /> */}
      <h1>
        Dokkyo-Info.
      </h1>
    </div>

  )
}

export function Header() {

  return (
    <div className="flex justify-between item-center size-auto">
      <Link
        href={'/'}
        className="object-fit"
      >
        <Logo />
      </Link>
      <section className={"flex px-5 gap-5 py-5 h-fit"}>
        <div className={` ${JosefinSans.className} hidden md:flex gap-x-3 text-sm md:text-xl lg:text-2xl list-none md:gap-x-5 lg:gap-x-7 font-normal ${JosefinSans.className}`}>
          <Link href='/'>Home</Link>
          <Link href='/clubs'>Clubs</Link>
          <Link href='/prepare'>Seminar</Link>
          <Link href='/prepare'>Article</Link>
          <Link href='/prepare'>Other</Link>
        </div>
        <Link href={'/prepare'} className={`btn bg-mauve-700 p-1 w-auto px-2 h-[30px] ${JosefinSans.className} rounded-sm text-center text-white`}>
          Sigh In
        </Link>
        {/* <FontAwesomeIcon icon={byPrefixAndName.fas['bars']} /> */}
      </section>

    </div>
  )
}




// export function Header() {
//   return (
//     <header className="flex items-center justify-between h-20 px-8 bg-white shadow-md">

//       <Logo />

//       <nav className="hidden md:flex items-center gap-8 text-gray-700 font-medium">
//         <Link href="/">Home</Link>
//         <Link href="/clubs">Club</Link>
//         <Link href="/seminar">Seminar</Link>
//         <Link href="/article">Article</Link>
//         <Link href="/calendar">Calendar</Link>
//       </nav>

//       <Link
//         href="/blog"
//         className="bg-violet-500 text-white px-4 py-2 rounded-md hover:bg-violet-600 transition"
//       >
//         Sign In
//       </Link>
//     </header>
//   )
// }

// function Logo() {
//   const imgPath = '/images/dokkyo-info-logo.png'

//   return (
//     <div>
//       <img
//         src={imgPath}
//         alt="Logo"
//         className="block w-[120px] object-contain"
//       />
//     </div>
//   )
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta charSet="utf-8" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${KosugiMaru.className} antialiased bg-white dark:bg-[#0a101d]`}
      >

        <Header />
        <main>
          {children}
        </main>

        <Menu />

        {/* <Footer /> */}
        <footer className="bg-[#141b2e] text-[#8593a8] text-center py-6 mt-16 gap-y-10 z-0">
          <section className="w-fit h-fit item-center justify-center m-auto bg-[#232E40] py-4 px-3 md: py-3, px-4 gap rounded-[7px]">

            <div className="flex justify-center pb-3">
              <div className="animate-pulse h-3 w-3 bg-blue-500 rounded-full"></div>
            </div>
            <p className={`${UbuntuFont.className} text-sm md:text-normal`}>Server Running...</p>
          </section>

          <p className={`${JosefinSans.className} text-sm pt-5 pb-30 md:pb-0`}>
            © 2026 Dokkyo-Info. All rights reserved.
          </p>
        </footer>

      </body>
    </html>
  );
}

function Menu() {
  return (
    <div className="m-auto flex justify-center text-center text-[#0a101d] md:hidden fixed bottom-3 left-1/2 -translate-x-1/2 w-2/3 h-fit py-3 rounded-full gap-5 text-3xl bg-white shadow-2xl z-1">
      <Link href='/'><FontAwesomeIcon icon={faHouse} /></Link>
      <Link href='/clubs'><FontAwesomeIcon icon={faPeopleRobbery} /></Link>
      <Link href='/prepare'><FontAwesomeIcon icon={faChalkboardUser} /></Link>
      <Link href='/prepare'><FontAwesomeIcon icon={faSchool} /></Link>
    </div>
  )
}

// export function movingDot() {

//   type Coordinate = {
//     x: number;
//     y: number;
//   };

//   const [dotPosition, setDotPosition] = useState<Coordinate>({
//     x: 0,
//     y: 0
//   });

//   return (
//     <div
//       onPointerMove={e => {
//         setDotPosition({
//           x: e.clientX,
//           y: e.clientY
//         });
//       }}
//     />
//   )
// }


// white, red, orange, amber, yellowlime, green,
// emerable, teal, cyan, sky, blue, indigo, violet, 
// purple, fuchsia, pink, rose, slate, gray, zinc, 
// neutral, stone, mauve, olive, mist, taupe, 